trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt update
      sudo apt install curl
  displayName: 'Instalando Curl'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin'
  displayName: 'Instalando grype'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  displayName: 'Install Docker 17.09.0-ce'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd web_front_pages
      docker build -t web_front_pages .
  displayName: 'Docker Build'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'grype web_front_pages'
  displayName: 'Vulnerability Images'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'JP_AWS'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'web_front_pages'
    repositoryName: 'web_front_pages'
    autoCreateRepository: true
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'JP_AWS'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 
      aws ecs update-service --cluster Dev_cluster --service service-frontend --force-new-deployment
  displayName: 'New Service'
